feat(.github/workflows): add pretty print to api_spec.yaml
A new feature which adds a step in the workflows to implement 'pretty printing' using jq to the api_spec.yaml. This process is aimed at improving the readability and manageability of our yaml files by neatly formatting them. It should be noted that this change also makes sure we upload the prettified yaml file as part of the workflow artifact, not the original one. Hence, the path in 'upload-artifact' action has been modified accordingly. 📚🛠️

diff --git a/.github/workflows/debug.yml b/.github/workflows/debug.yml
--- a/.github/workflows/debug.yml
+++ b/.github/workflows/debug.yml
@@ -23,6 +23,7 @@ jobs:
       - name: Encode the file with base64
         run: |
           base64 -w 0 api_spec.yaml > api_spec.base64 || echo "Encoding failed"
+          jq . api_spec.yaml > api_spec_pretty.yaml || echo "Pretty printing failed"
 
       - name: Set the size and time taken as output parameters
         run: |
@@ -32,4 +33,4 @@ jobs:
         uses: actions/upload-artifact@v2
         with:
           name: api-spec
-          path: api_spec.yaml
+          path: api_spec_pretty.yaml
